# Generated by Django 3.0.4 on 2020-07-18 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_vendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vendor',
        ),
    ]
