# Generated by Django 3.0.4 on 2020-07-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20200719_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scooter',
            name='brand',
            field=models.CharField(choices=[('BI', 'bird'), ('WI', 'wind'), ('LI', 'lime')], max_length=2),
        ),
    ]
