# Generated by Django 3.0.4 on 2020-07-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20200719_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scooter',
            name='status',
            field=models.CharField(choices=[('NE', 'new'), ('US', 'used'), ('RE', 'repair')], max_length=2),
        ),
    ]
