# Generated by Django 3.0.4 on 2020-07-20 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20200719_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scooter',
            name='battery',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='city',
            field=models.CharField(choices=[('Tel Aviv', 'Tel Aviv'), ('Ramat Gan', 'Ramat Gan'), ('Givatayim', 'Givatayim')], default='Tel Aviv', max_length=10),
        ),
    ]
