# Generated by Django 3.0.4 on 2020-07-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20200720_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scooter',
            name='brand',
            field=models.CharField(choices=[('bird', 'bird'), ('wind', 'wind'), ('lime', 'lime')], max_length=4),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('used', 'used'), ('repair', 'repair')], max_length=6),
        ),
    ]
